### PR TITLE
Fix reversed actions in nested/indented lists

### LINKED ISSUE #510: Nested list items of different type highlight both buttons
## Steps to reproduce
1. Create an ordered list with 2 list items.
2. Indent the 2nd one.
3. Toggle its list type by toggling the unordered list button.

This can also be done by reversing the ordered -> unordered list types.

#### What did you expect?

I'd expect only the unordered list button to be highlighted, as it's the active one at this level of indentation.

#### What happened instead?

Both list buttons are highlighted. This is a bit confusing, as I'd expect the **highlighted** ordered list button to remove the external list type, 'reversing' the previous action, as most highlighted action buttons work, but instead it toggles the list type for the internal list items.

## Screenshot

This screenshot shows what it looks like at the moment, with the 'Now ordered' list item being selected.

image

### PR DESCRIPTION
**Pull request by aringenbach**
* Fixes issue with unmatching(type) indented lists marking both list types as reversed
* Renaming `active_button` to `reversed_action` to match rest of the naming

Fixes #510

### CODE REVIEW

File: crates/wysiwyg/src/tests/test_menu_state.rs [hunk 1]
```diff
@@ -189,6 +189,28 @@ fn formatting_is_disabled_when_selection_covers_inline_code_node_and_others() {
...
+    assert!(!model.action_is_reversed(ComposerAction::UnorderedList));
+}
+
+#[test]
+fn selecting_cross_matching_indented_list_include_list_type() {
+    let model =
+        cm("<ol><li><p>It{em 1</p><ol><li>Item 1}|A</li></ol></li></ol>");
+    assert!(model.action_is_reversed(ComposerAction::OrderedList));
+}
+
```
Comment (jmartinesp) [inline crates/wysiwyg/src/tests/test_menu_state.rs:213]: Could it be worth it to add tests for 'deep' nested lists (`ul > ol > ul`)?

**Review by jmartinesp — APPROVED** [review]
LGTM, I just have a suggestion.
