### PR TITLE
Fix menu state in empty formatted paragraphs/list items

### LINKED ISSUE #551: Empty paragraph/list item with formatting don't return expected menu state
Test cases that don't work:

```rust
#[test]
fn empty_paragraph_with_formatting_computes_expected_menu_state() {
    let model = cm("<p><em>abc</em></p><p><em>|</em></p>");
    assert!(model.action_is_reversed(ComposerAction::Italic));
}

#[test]
fn empty_list_item_with_formatting_computes_expected_menu_state() {
    let model = cm("<ol><li><em>abc</em></li><li><em>|</em></li></ol>");
    assert!(model.action_is_reversed(ComposerAction::Italic));
}
```

### PR DESCRIPTION
**Pull request by aringenbach**
Fixes #551

### CODE REVIEW

File: crates/wysiwyg/src/dom/range.rs [hunk 1]
```diff
@@ -399,6 +399,22 @@ impl Range {
...
+            .filter(|l| {
+                let mut found = true;
+                if let Some(ancestor_of) = ancestor_of {
+                    found = l.node_handle.is_ancestor_of(ancestor_of);
+                }
+                found && !l.is_leaf()
+            })
+            .max()
+    }
+
```
Comment (alunturner) [inline crates/wysiwyg/src/dom/range.rs:417]: Could this be a call to `deepest_node_of_kind` where it adds the container kind to the function call for you?

**Review by alunturner — COMMENTED** [review]
Just the one comment, but looks good to me other than that

File: crates/wysiwyg/src/dom/range.rs (hunk 1 above)
Comment (aringenbach) [reply crates/wysiwyg/src/dom/range.rs:417]: If it was only for formatting we'd still have to rework the `deepest_node_of_kind` func because it just compares `kind` and things like `kind() == DomNodeKind::Formatting(_)` is not allowed.
Moreover we probably want to include any type of container that might be present in between since it could be links, lists, etc and these should update the menu state as well.

**Review by alunturner — APPROVED** [review]
