### PR TITLE
[Android] Fix crash due to out of bounds error

### LINKED ISSUE #839: Crash on EXA: StringIndexOutOfBoundsException
Reported by rageshake on Element X Android 0.2.3 (and previous version): https://github.com/vector-im/element-x-android-rageshakes/issues/833

> Thread: main, Exception: java.lang.StringIndexOutOfBoundsException
at android.text.SpannableStringBuilder.(SpannableStringBuilder.java:63)
at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1198)
at io.element.android.wysiwyg.inputhandlers.InterceptInputConnection.setComposingText(SourceFile:47)

Sorry, I have no more information, but [several rageshakes](https://github.com/vector-im/element-x-android-rageshakes/issues?q=is%3Aissue+is%3Aopen+StringIndexOutOfBoundsException) have been reported, this can give some clue.

### PR DESCRIPTION
**Pull request by jonnyandrew**
## Problem

The crash is caused by attempting to access an invalid index in text returned from the Rust model. 

## Solution

The problem occurs while attempting to restore the background colour of Japanese text that is being composed. However this functionality is neither in a working state nor tested so this fix simply removes the offending code so that it can be readded in a working state.

- Fixes #839

### CODE REVIEW

File: platforms/android/library/src/main/java/io/element/android/wysiwyg/inputhandlers/InterceptInputConnection.kt [hunk 1]
```diff
@@ -78,6 +76,7 @@ internal class InterceptInputConnection(
         return baseInputConnection.performPrivateCommand(action, data)
     }
 
+    @RequiresApi(Build.VERSION_CODES.S)
```
Comment (jonnyandrew) [inline platforms/android/library/src/main/java/io/element/android/wysiwyg/inputhandlers/InterceptInputConnection.kt:79]: Unrelated lint fix

**Review by jmartinesp — APPROVED** [review]
LGTM, last time I tested this it was working, but it was a long time ago, so we can delete it if it's causing more trouble than it should.
